[package]
name = "hk"
version = "0.1.0"
edition = "2021"
description = "A tool for managing git hooks"
license = "MIT"
repository = "https://github.com/jdx/hk"
documentation = "https://hk.jdx.dev"
homepage = "https://hk.jdx.dev"
build = "build.rs"
include = ["src", "Cargo.toml", "Cargo.lock", "README.md", "LICENSE", "build.rs", "pkl"]

[dependencies]
chrono = "0.4"
clap = { version = "4", features = ["derive"] }
console = "0.15"
dirs = "6"
duct = "0.13.7"
ensembler = "0.1.0"
git2 = "0.20"
globset = "0.4.15"
indexmap = { version = "2", features = ["serde"] }
itertools = "0.14"
log = "0.4"
miette = { version = "7", features = ["fancy", "syntect-highlighter"] }
rpkl = "0.4"
serde = { version = "1", features = ["derive"] }
serde_with = "3.12.0"
serde_yaml = "0.9.34"
serde_json = "1"
tera = "1.20.0"
thiserror = "2.0.11"
tokio = { version = "1", features = ["full"] }
toml = "0.8"
xx = { version = "2", features = ["http", "hash", "rustls"] }
strum = { version = "0.26", features = ["derive"] }

[build-dependencies]
rpkl = "0.4"
serde = { version = "1", features = ["derive"] }
strum = { version = "0.26", features = ["derive"] }

[features]
default = ["git2/vendored-libgit2"]
